org: zmrfzn
app: otel-sls-sdk-dev
service: otel-sls-sdk
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  tracing:
    lambda: false
    apiGateway: false

functions:
  api:
    handler: index.handler
    environment:
      NODE_OPTIONS: "--require ./otel-wrapper"
      OTEL_SERVICE_NAME: "Node-Lambda-Otel-SDK"
      EXPRESS_OTEL_API_ENDPOINT: "http://3.230.230.121/v3/api"
      NR_LICENSE: ${ssm:/nr_experiments_ingest_key}
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net:4317
      ENABLE_FS_INSTRUMENTATION: false

    events:
      - httpApi: "*"

dashboard:
  disableMonitoring: true

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
